openapi: "3.0.0"
info:
  title: "Weatherapp API"
  description: "Application Programming Interface for managing weather data."
  version: "1.0"

paths:
  /weather:
    get:
      operationId: api.weather.get_weather  # ✅ Fix: Matches api/weather.py
      summary: "Get weather information of all cities in the system."
      responses:
        200:
          description: "List of weather information for all cities."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Weather"

    post:
      operationId: api.weather.add_weather  # ✅ Fix: Correct namespace (was api.people)
      summary: "Add weather information of a new city."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Weather"
      responses:
        201:
          description: "Weather info added successfully."

components:
  schemas:
    Weather:
      type: object
      properties:
        id:
          type: integer
        city:
          type: string
        temperature:  # ✅ Fix typo (was "temprature")
          type: number
          format: float
        humidity:
          type: number
          format: float
