version: "3.8"

services:
  flaskapp:
    build: 
      context: ./weatherInfoService
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: config.py
      MYSQL_HOST: mysqldb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
      MYSQL_DB: weather_db
    depends_on:
      - mysqldb

  mysqldb:
    build:
      context: ./mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: weather_db
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
