version: "3.8"

services:
  flaskapp:
    build: 
     context: ./weatherInfoService     
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py