# swagger.yml

openapi: 3.0.0
info:
  title: "Weather information Service"
  description: "An Api for controlling weather information through CRUD services."
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Weather:
      type: "object"
      required:
        - city
        - temperature
        - humidity
        - windspeed
      properties:
        city:
          type: "string"
        temperature:
          type: "number"
          format: "float"
        humidity:
          type: "number"
          format: "float"
        windspeed:
          type: "number"
          format: "float"
  parameters:
    city:
      name: "city"
      description: "name of the city to get weather information"
      in: path
      required: True
      schema:
        type: "string"



paths:
  /weather:
    get:
      operationId: "weather.get_all"
      tags:
        - Weather
      summary: "retrieve all weathers information"
      responses:
        "200":
          description: "Successfully read weather list"
    post:
      operationId: "weather.create"
      tags:
        - Weather
      summary: "Create a new weather record"
      requestBody:
          description: "weather information to be created"
          required: True
          content:
            application/json:
              schema:
                x-body-name: "weather"
                $ref: "#/components/schemas/Weather"
      responses:
        "201":
          description: "Successfully created weather information"
  /weather/{city}:
    get:
      operationId: "weather.get_one"
      tags:
        - Weather
      summary: "Read one weather information"
      parameters:
        - $ref: "#/components/parameters/city"
      responses:
        "200":
          description: "Successfully read weather information" 
    put:
      operationId: "weather.update"
      tags:
        - Weather
      summary: "Update a weather info"
      parameters:
        - $ref: "#/components/parameters/city"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "weather"
              $ref: "#/components/schemas/Weather"
      responses:
        "200":
          description: "Successfully updated weather information"
    delete:
      tags:
        - Weather
      operationId: "weather.delete"
      summary: "Delete a weather information"
      parameters:
        - $ref: "#/components/parameters/city"
      responses:
        "204":
          description: "Successfully deleted"
      